### ISSUE TITLE
Steps for finishing the uploader 0.0.1

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#103]
## Paratii-db

- [x] **Deploy** paratii-db (is on http://db.paratii.video/api/v1/)
- [x] Make paratii-db actually read the events from our video
 - [x] Must be on https: https://github.com/Paratii-Video/devops/issues/37

#### Integrate paratii-db with paratii-lib
  - [x] Implement `paratii.db.vids.get()`: https://github.com/Paratii-Video/paratii-lib/issues/99
  - [x] Implement `paratii.db.vids.search()` and in particular `paratii.db.vids.search(owner=...)`: https://github.com/Paratii-Video/paratii-lib/issues/35

#### Integrate with paratii-portal:
  - [x] Make sure we use `paratii.core` for fetching info from the blockchain: https://github.com/Paratii-Video/paratii-portal/issues/129
  - [x] When a user returns, fetch the list of her videos and show those on the upload page.

## IPFS, transcoding, paratii-protocol

- [x] Progress updates on upload: https://github.com/Paratii-Video/paratii-lib/issues/98
- [x] Integrate progress updates on save: https://github.com/Paratii-Video/paratii-portal/issues/131
- [x] Test it

## Portal uploader UX

- [x] Decide UX for version 0.1. (uploader, limited functionality) (call on monday with pedro)
- [x] Make the designs
- [x] Implement CSS
- [x] fix all issues in https://github.com/Paratii-Video/paratii-portal/projects/1

##  Player

- [x] Make the loading experience smoother (start up node in the background, etc).
- [x] Set the correct headers for sharing.https://github.com/Paratii-Video/paratii-portal/issues/157
- [x] Consider how exactly we do the clappr integration: https://github.com/Paratii-Video/paratii-mediaplayer/issues/37

## Make the portal user-friendly also with limited functionality

- [x] Hide/alert for things we do not use (like "rip form youtube") and try to give the user an reasonable experience even if lost functionality is not there yet.
- [x] Implement 404 page

## Staking

- [x] write simple staking contract:  https://github.com/Paratii-Video/paratii-contracts/issues/37
- [x] Add minimal "staking" functionality to paratii-lib - https://github.com/Paratii-Video/paratii-lib/issues/101
- [x] create modal for staking: https://github.com/Paratii-Video/paratii-portal/issues/163

## Voucher

General idea is described here: https://github.com/Paratii-Video/paratii-portal/issues/104. We'd need:

- [x] A contract to manage the vouchers https://github.com/Paratii-Video/paratii-contracts/issues/36
- [x] Paratii-lib extensions for vouchers https://github.com/Paratii-Video/paratii-lib/issues/103
- [x] UX integration in the portal https://github.com/Paratii-Video/paratii-portal/issues/115

## Guide
- [x] create component for guide https://github.com/Paratii-Video/paratii-portal/issues/119
- [x] write contents for the guide: https://github.com/Paratii-Video/paratii-portal/issues/133

## Devops

- [x] deploy pratii portal
- [x] point portal.paratii.video to this newly deployed portal
- [x] Deploy paratii-db https://github.com/Paratii-Video/paratii-db/issues/8
- [x] Deploy latest version of the contracts on the blockchain
