### ISSUE TITLE
Implement Vouchers

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#104]
_[still brainstorming]_

## What we wanna do

Give a select group of uploaders access to the portal, and give them some PTI to spend (for staging in TCRs).

## One way of doing it - use case

- Create 1-time usable vouchers. A voucher is simply a string/password/code.
- Send a voucher to each select user by mail. And a link.
- User arrives on this link, finds a "use voucher" page (doesn't need to be public).
- Inserts the voucher.
- 25 PTIs show up on his account.

## How to make it

It could be all done by a smart contract, actually: the form sends a transaction the blockchain that triggers the transfer. The "extra info" (who it was inteded for) we can just keep in an excel spreadsheet or something.

- [x] a contract to manage the vouchers https://github.com/Paratii-Video/paratii-contracts/issues/36
- [x] paratii-lib extensions for vouchers https://github.com/Paratii-Video/paratii-lib/issues/103
- [x] UX integration in the portal https://github.com/Paratii-Video/paratii-portal/issues/115

**Comment by felipegaucho** [comment]
Thanks @milankragujevic and @jellegerbrandy ! Up and running.
