### ISSUE TITLE
Missing things to have a proper login flow

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#492]
## Secure wallet flow:

- [x] check for password security #486 
- [x] back button on "profile" should be removed #490
- [x] show "secure account"  flow only when account is not secure #489
- [x] some changes in texts: #491
- [x] hooks #483
- [x] hitting the return button => click on "continue" in the password forms
- [x] the password form for "log in" (i.e. the one you see on first visit) should be blocking and not closeable, i think.
- [x] have decent weak-password-feedback #498
- [x] make 12 words selectable #499
- [x] bug in unlocking wallet after securing #500
- [x] email cannot be empty in paratii-js #488
- [x] decide where to store email
- [x] show the "password" screen of the secured not on each load of the portal, but only when the user wants to access "secure" parts (i.e. the same places where we ask him to secure his account)

## Things that would surely be nice to have:
- [ ] secure flow should be implemented in the embedded version as well https://github.com/Paratii-Video/paratii-portal/issues/527
- [ ] It also should provide alternative options like "you don't remember your password, you can restore your account here or create a new one here" #497
- [ ] store the email non-publicly: https://github.com/Paratii-Video/paratii-js/issues/225
- [ ] email confirmation https://github.com/Paratii-Video/paratii-portal/issues/510
- [ ] terms and conditions #493 
- [ ] a place to edit your name and email

**Comment by felipegaucho** [comment]
Since all missing things have their own issues, and there's a first full version of the flow online, closing this.
