### ISSUE TITLE
email confirmation set up

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#510]
Email confirmation flow:

After the user registers with an email the following happens:

* We send the user an email with a confirmation link
* The users clicks on the link, he gets some PTI, and the confirmation is stored 

In detail, we will have a signalling contract on the blockchain that is used to distribute the PTI and register the confirmation at the same time.

- [x] `PTIDistributor.sol` contract. This is an `Owned` contract. It holds some PTI, and has a `transfer(_toAddress, _amount, _code)` function that transfers `_amount` PTI to `_toAddress` and logs a `LogDistribute(_toAddress, _amount, _code)` event. The `_code` is used to link the transfer to a specific data record.

 I propose to use `paratii-db` as the initiator/coordinator of the whole thing:

- [x] user clicks "submit" at the end of the "create your account" flow
- [ ] `paratii-db` receives the submitted email address (at the moment, because it will receive the `LogCreateUser`  event, but this will change)
- [x] paratii-db generates a confirmation code `_code`, creates a `PTIDistributor.transfer(..)` transaction, and signs it with the `_owner` account of the `PTIDistributor`.https://github.com/Paratii-Video/paratii-db/issues/137
- [x] paratii-db creates the email body that includes a link to the given transaction. Unfortunately, we cannot send GET requests directly to the blockchain, so we must pass trhough some intermediate service :-(. So the link is of the form portal.paratii.video/confirmEmail?payload=0x12absomefairlylargestring) https://github.com/Paratii-Video/paratii-db/issues/137
- [x] and instructs the email service to send out an email https://github.com/Paratii-Video/paratii-db/issues/137
- [x] After the user  clicks on the link, a service transforms the requests into a POST request and forwards is to the blockchain (<- can this be done by nginx?) https://github.com/Paratii-Video/paratii-db/issues/136
- [x] `paratii-db` listens for the `LogDistribute` event, checks the address adn the code, and flags the email as "confirmed"

**Comment by geckoslair** [comment]
idea for the http service:

1. portal send to the user an email with a signed (from paratii) tx
2. the user click on the email url (that contains signed tx)
3. a little service transform tx GET param in a tx POST JSON RPC param
4. the json rpc request is sent directly to the node.
5. something (a contract) flag the address as valid and gives to the user some PTI

@felipegaucho @jellegerbrandy @ya7ya ?

**Comment by felipegaucho** [comment]
@geckoslair what's the updated status in the list :neckbeard: ?

**Comment by felipegaucho** [comment]
👊  👏 😍 @geckoslair
