### ISSUE TITLE
January Sprint: checklist

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#56]
Working on branch https://github.com/Paratii-Video/paratii-portal/tree/8-uploader

# get upload tool working

- [x] Deploy  contracts for registering vids to the blockchain  and ipfs
- [x] integrate with paratii-lib
- [ ] Pass configuration to portal: #51 
- [ ] wallet management to portal
- [ ] Create pages and forms for upload in portal #8 
- [ ] testing and finetuning [<- **big task**]

# implement throttling via tokens

https://github.com/Paratii-Video/wiki/wiki/Protocol-Description:-Upload-Video

- [ ] setup a loan/gift system
- [ ] write the contracts
- [ ] integrate with paratii-lib
- [ ] integrate with paratii-portal

**Comment by jellegerbrandy** [comment]
Contract registry is at 0x0B101ff870F8BAd6c437C45eCb2964D7e8034593

**Comment by jellegerbrandy** [comment]
there are other issues tracking this
